### ISSUE TITLE
Feature request: fakeit-lite

### ISSUE THREAD

**Issue by tabrindle** [bentonam/fakeit#148]
The couchbase integration is literally the shit. But not always necessary, and whenever fakeit is installed, it installs couchbase-promises, which builds the native couchbase binary, adding a lot of time to install, and some native dependencies - g++ and similar. 

I propose a secondary package something to the effect of fakeit-lite, which has everything but the dependency on couchbase.

**Comment by tjbenton** [comment]
I agree, having the couchbase package make the install incredibly slow. Instead of dealing with a secondary package I would rather use something like this https://www.npmjs.com/package/npmi which will install package if it's not installed already.

**Comment by tabrindle** [comment]
Our team currently uses https://www.npmjs.com/package/install-subset which allows you to only install some top level dependencies on demand. We don't always need fakeit. 

However I think a restructure of this project makes a better DX. You could create a core library for the data generation and different adapters based on data output which could be installed separately.

**Comment by tjbenton** [comment]
Closing this issue in favor of #164
