### ISSUE TITLE
Support For Couchbase Server 5.0 RBAC

### ISSUE THREAD

**Issue by brantburnett** [bentonam/fakeit#156]
Currently, you can only supply a bucket password for Couchbase on the command line.  To support Couchbase Server 5.0 we need the ability to supply a username and password.

**Comment by bentonam** [comment]
@brantburnett We have a dependency on the [couchbase-promises](https://github.com/dsfields/couchbase-promises) project, I have sent them a [Pull Request](https://github.com/dsfields/couchbase-promises/pull/21) to update the NodeJS SDK to v2.4.0 which adds support for authenticating against CB 5.x, once that is merged and updated in NPM I will update FakeIt

**Comment by brantburnett** [comment]
@bentonam 

Looks like your pull request was merged and released for couchbase-promises.  If you like I'd be happy to take on this issue, seems like it might be fun.

**Comment by bentonam** [comment]
@brantburnett if you'd like to take it on that'd be great.  I started to work on it when that PR was merged and just have been caught up and haven't had a chance to get it completed.

**Comment by brantburnett** [comment]
@bentonam 

Thanks for merging my work, I see support is there in version 1.2.0.  I've updated the [CouchbaseFakeIt](https://github.com/brantburnett/couchbasefakeit) Docker image to include this version and everything appears to be working great.

**Comment by tjbenton** [comment]
@brantburnett thanks for the contribution to the project
