### ISSUE TITLE
Timeout option throws false error "must be a number"

### ISSUE THREAD

**Issue by clupo** [bentonam/fakeit#171]
Running this command throws the error

`fakeit couchbase --bucket "Authentication" -u "u" -p "password" "/startup/$bucketName/models" --timeout 10000`

![image](https://user-images.githubusercontent.com/29711376/33497783-13890678-d69d-11e7-9a8e-39e2882f30cd.png)

This is using fakeit version 1.2.0 running in ubuntu:14.04

**Comment by tjbenton** [comment]
@clupo This has been fixed in #172 and will be released in the next release. Hopefully later today.

**Comment by clupo** [comment]
well that was fast :)

**Comment by bentonam** [comment]
@clupo working on verifying a couple things and then we'll try to get a release out at some point today.  Thanks for reporting the issue!
